### PR TITLE
Fix links in footer

### PR DESCRIPTION
**Pull request by jpmckinney**
Please also add represent.poplus.org as in https://github.com/poplus/home-poplus/pull/70

### CODE REVIEW

**Comment by jpmckinney** [comment]
@hecticjeff @zarino @wrightmartin Ping?

**Comment by jpmckinney** [comment]
@hecticjeff @zarino @wrightmartin 4 months and counting for this _suuuper_ simple pull request that just fixes a few links. Please also add represent.poplus.org as in poplus/home-poplus#70

**Comment by chrismytton** [comment]
@jpmckinney Thanks! :tada:

**Comment by chrismytton** [comment]
Represent Boundaries link added in https://github.com/mysociety/sayit.poplus.org/commit/e31e18728451a65e58f4c8fbc991e7cb19c268a5

**Pull request merged**
